### ISSUE TITLE
Incorrect typo field

### ISSUE THREAD

**Issue by AdedayoMj** [octotravel/octo-types#11]
Hi, please could you modify this  `questionAswers` to `questionAnswers`
https://github.com/octotravel/octo-types/blob/3ac8989a0bc21293c9a13979270db0b3bab68f78/src/types/Booking.ts#L146

**Comment by dominikchrastek** [comment]
fixed here: https://github.com/octotravel/octo-types/commit/e1aebd5600daa2d0372b91564d241d6d09cadb0b
